services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api1:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - INSTANCE_ID=Node-1
    depends_on:
      - redis

  api2:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - INSTANCE_ID=Node-2
    depends_on:
      - redis

  api3:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - INSTANCE_ID=Node-3
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - API1_HOST=api1
      - API2_HOST=api2
      - API3_HOST=api3
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2
      - api3
