FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Use template for IP injection
COPY default.conf.template /etc/nginx/templates/default.conf.template

# Copy the master startup script
COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

# Remove the default nginx entrypoints because we take full control
RUN rm -f /docker-entrypoint.d/20-envsubst-on-templates.sh
RUN rm -rf /docker-entrypoint.d/*

EXPOSE 80

# Run our custom hot-swapping script
CMD ["/startup.sh"]
