FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Use template for IP injection
COPY default.conf.template /etc/nginx/templates/default.conf.template
COPY resolve-ips.sh /docker-entrypoint.d/01-resolve-ips.sh
RUN chmod +x /docker-entrypoint.d/01-resolve-ips.sh

# Remove the default nginx envsubst script since we handle it in our custom script
RUN rm -f /docker-entrypoint.d/20-envsubst-on-templates.sh

EXPOSE 80
