services:
  - type: redis
    name: rate-limiter-redis
    ipAllowList: []
    plan: free

  - type: pserv
    name: api1
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: rate-limiter-redis
          property: connectionString
      - key: INSTANCE_ID
        value: Node-1

  - type: pserv
    name: api2
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: rate-limiter-redis
          property: connectionString
      - key: INSTANCE_ID
        value: Node-2

  - type: pserv
    name: api3
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: rate-limiter-redis
          property: connectionString
      - key: INSTANCE_ID
        value: Node-3

  - type: web
    name: rate-limiter-nginx
    env: docker
    dockerfilePath: Dockerfile.nginx
    plan: free
    envVars:
      - key: API1_HOST
        fromService:
          type: pserv
          name: api1
          property: host
      - key: API2_HOST
        fromService:
          type: pserv
          name: api2
          property: host
      - key: API3_HOST
        fromService:
          type: pserv
          name: api3
          property: host
